Implement missing RecipeManagerOperation functionality
CSC207-2022F-UofT/course-project-gordon-recipe pull request #30
Opened 2022-12-03 09:23 UTC by lukekrikorian

Closes #29

2022-12-03 23:28 UTC, shape-warrior-t reviewed
Haven't tested anything yet, but some initial feedback, suggestions, and comments:
- `toString` overrides are nice, though I'm not sure the format of the ingredients will work in every scenario; something more like `[ingredient] - [quantity]` would be more universal in my opinion. Though I'm not sure how likely that is to actually come into play.
- All of the stuff in the Colour class is much-appreciated... though at this point it's becoming more of a "formatted printing" class than a "colour" class. :P
- ...I might change `getListIndexInput` so that it takes in a list of any object, not just strings. ...Also, it kinda looks like `chooseOperation` could be implemented in terms of `chooseFromList`?
- I prefer `0 <= index && index < list.size()` over `index >= 0 && index < list.size()` as a translation of `0 ≤ index < (list size)`, but ultimately that's just a matter of preference.
- Refer to what I said on Discord about adding the functionality of editing (read: deleting, mostly) recipe ingredients, tags, tools, and steps.

None of this is a compelling reason to refrain from merging the pull request in my opinion, so after I do some testing, I'll hopefully approve this pull request. Assuming I don't find any bugs.

2022-12-03 23:45 UTC, shape-warrior-t requested changes
Overall good based on testing, but one bug in `chooseFromList`: it errors when the user exits out from the selection, probably because it doesn't check for null.

2022-12-04 15:43 UTC, ActualX submitted a review, later dismissed

2022-12-04 17:25 UTC, lukekrikorian commented
> * All of the stuff in the Colour class is much-appreciated... though at this point it's becoming more of a "formatted printing" class than a "colour" class. :P

Haha yes, I'm not sure it's worth changing the name but it does feel like it's encompassing more functionality than it seems like it would.

> * ...I might change `getListIndexInput` so that it takes in a list of any object, not just strings. ...Also, it kinda looks like `chooseOperation` could be implemented in terms of `chooseFromList`?

`chooseOperation` could be implemented in terms of `chooseFromList` but I think the UX is better typing what you want e.g. "create recipe" instead of an index.

2022-12-04 17:33 UTC, jasala10 approved these changes

2022-12-04 17:34 UTC, merged